### Create New Users
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "jojo",
  "email": "jojo@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Login
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mjjj@test.com",
  "password": "password"
}

### User index Test 
GET http://localhost:3000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NjQyMDMyODN9.0tvn5Kn_sEKH_nujuuZ5X1q82kJuAgJB8cM8NGSzqaU
